# Generated by Django 3.2.13 on 2022-07-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name': 'Tweet', 'verbose_name_plural': 'Accounts Monitoring'},
        ),
        migrations.AlterModelOptions(
            name='repliesback',
            options={'verbose_name': 'Tweet', 'verbose_name_plural': 'Your Replies Count'},
        ),
        migrations.AlterModelOptions(
            name='repliescount',
            options={'verbose_name': 'Tweet', 'verbose_name_plural': 'Replies Count'},
        ),
        migrations.AlterModelOptions(
            name='retweetback',
            options={'verbose_name': 'Tweet', 'verbose_name_plural': 'Your Retweets Count'},
        ),
        migrations.AlterModelOptions(
            name='retweets',
            options={'verbose_name': 'Tweet', 'verbose_name_plural': 'Retweets Count'},
        ),
        migrations.AlterModelOptions(
            name='tweetback',
            options={'verbose_name': 'Tweet', 'verbose_name_plural': 'Your Tweets Like Count'},
        ),
        migrations.AlterModelOptions(
            name='tweets',
            options={'verbose_name': 'Tweet', 'verbose_name_plural': 'Tweets Like Count'},
        ),
    ]
